Resolving a test error on Windows
It's odd that this only happens on Windows.
---
ImportError: Failed to import test module: test_verify
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.13.9\x64\Lib\unittest\loader.py", line 137, in loadTestsFromName
    module = __import__(module_name)
  File "D:\a\smart-tests-cli\smart-tests-cli\tests\commands\test_verify.py", line 5, in <module>
    from smart_tests.commands.verify import check_java_version, compare_java_version, compare_version
  File "D:\a\smart-tests-cli\smart-tests-cli\smart_tests\commands\verify.py", line 17, in <module>
    from ..utils.java import get_java_command
  File "D:\a\smart-tests-cli\smart-tests-cli\smart_tests\utils\java.py", line 8, in <module>
    from smart_tests.commands.record.case_event import TestPathBuilder
  File "D:\a\smart-tests-cli\smart-tests-cli\smart_tests\commands\record\__init__.py", line 4, in <module>
    from .build import build
  File "D:\a\smart-tests-cli\smart-tests-cli\smart_tests\commands\record\build.py", line 22, in <module>
    from .commit import commit
  File "D:\a\smart-tests-cli\smart-tests-cli\smart_tests\commands\record\commit.py", line 21, in <module>
    from ...utils.java import cygpath, get_java_command
ImportError: cannot import name 'cygpath' from partially initialized module 'smart_tests.utils.java' (most likely due to a circular import) (D:\a\smart-tests-cli\smart-tests-cli\smart_tests\utils\java.py)
---